stages:
  download:
    cmd: curl https://www.sqlitetutorial.net/wp-content/uploads/2018/03/chinook.zip
      --output data\chinook.zip
    deps:
    - https://www.sqlitetutorial.net/wp-content/uploads/2018/03/chinook.zip
    outs:
    - data\chinook.zip

  unzip:
    cmd: tar -xf data\chinook.zip -C data
    deps:
    - data\chinook.zip
    outs:
    - data\chinook.db

  convert_to_graph:
    cmd: python convert_to_graph.py
    deps:
    - convert_to_graph.py
    - data\chinook.db
    outs:
    - data\graph.bin

  train:
    cmd: python train.py
    deps:
    - train.py
    - setup.py
    - dataloader.py
    - data\graph.bin
    params:
    - train
    metrics:
    - dvclive/metrics.json
    plots:
    - dvclive/plots/metrics:
        x: step
metrics:
- dvclive/metrics.json
plots:
- dvclive/plots/metrics:
    x: step
