train:
  target_edge:
    - playlists
    - hasTrack
    - tracks

  num_val: .15
  num_test: .00

  num_layers: 6
  num_neighbors: 20


  batch_size: 512
  learning_rate: .001
  hidden_channels: 30
  dropout: .5
  epochs: 100
  norm: BatchNorm
