train:
  random_seed: 10

  target_edge:
  - playlists
  - hasTrack
  - tracks
  num_val: .15
  num_test: .00

  num_layers: 6
  num_neighbors: 15

  batch_size: 512
  learning_rate: 0.00944217210243299
  hidden_channels: 10
  dropout: 0.15
  epochs: 3
  norm: BatchNorm
